Pipeline Orchestration task
SpeciesConservationLandscapes/task_orchestration pull request #1
Opened 2021-11-26 23:10 UTC by gridcell

2021-11-26 23:11 UTC, gridcell commented
![](https://github.trello.services/images/mini-trello-icon.png) [Orchestration Task](https://trello.com/c/wgnZMbVk/340-orchestration-task)

2021-12-01 14:29 UTC, saanobhaai requested changes
Awesome -- but a couple of questions

2021-12-01 14:29 UTC, saanobhaai commented on Dockerfile
> +FROM python:3.9-slim-bullseye
Any reason not to pull from `scl3/task_base` (https://github.com/SpeciesConservationLandscapes/task_base/blob/master/Dockerfile)?

2021-12-01 14:29 UTC, saanobhaai commented on src/task.py
> +        self.exit_on_error = kwargs.get("exit_on_error") or False
Refactor to use base `raiseonfail` property?
https://github.com/SpeciesConservationLandscapes/task_base/blob/master/task_base/task.py#L36

2021-12-01 14:29 UTC, saanobhaai commented on src/task.py
> +                raise PipelineError("Task error")
I might need some reminding on where/why we're raising exceptions...

2021-12-01 14:29 UTC, saanobhaai commented on src/task.py
> +        return not has_errors or not self.exit_on_error
Would this be more readable as
`return has_errors and self.exit_on_error`
?

2021-12-01 14:29 UTC, saanobhaai commented on Dockerfile
> +COPY ./vm/scl-orchestration-vm.jinja .
I've managed to get confused... These files don't exist, but are part of the pipeline-devops. Maybe the Dockerfile and the devops/jinja stuff got moved but not cleaned up here?

2021-12-01 18:56 UTC, saanobhaai commented on Makefile
> +VM_IMAGE=scl/orchestration-vm
We should use `scl3` for consistency

2021-12-02 21:30 UTC, gridcell commented on src/task.py
> +        return not has_errors or not self.exit_on_error
I want the `run_group` outcome to be False, showing that it successfully ran, `return has_errors and self.exit_on_error` would say run_group is True if it did not run successfully

2021-12-03 23:11 UTC, merged